###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "John",
    "email": "john@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "user"
}

###
// Get All Users
GET http://localhost:5000/users

###
// Get Single User
GET http://localhost:5000/users/af56e244-f6e0-4078-8361-3e1c85336d43

###
// Update User
PATCH http://localhost:5000/users/af56e244-f6e0-4078-8361-3e1c85336d43
Content-Type: application/json

{
    "name": "Kaldeniz",
    "email": "kaldeniz@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

### 
// Delete User
DELETE http://localhost:5000/users/71ba1846-edf1-4af0-88a4-93613dd5214d

###
// Login User
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "kaldeniz@gmail.com",
    "password": "123456"
}

###
// Me
GET http://localhost:5000/me

### 
// Logout
DELETE http://localhost:5000/logout

###
// Get All Products
GET http://localhost:5000/products

###
// Post Data Product
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Product Kaldeniz 3",
    "price": 109999
}

###
// Get Single Product
GET http://localhost:5000/products/f7dafd4f-e642-497f-b8ee-3b56665b29e3

###
// Update Product
PATCH http://localhost:5000/products/f7dafd4f-e642-497f-b8ee-3b56665b29e3
Content-Type: application/json

{
    "name": "Product Kaldeniz Ketiga",
    "price": 109998
}

###
// Delete Product
DELETE http://localhost:5000/products/5e71a49a-41ce-499b-bd1b-76cc7d45617b